name: App Manager CI
on:
  push:
    branches: [main, preprod, staging, develop]
  pull_request:
    branches: [main, preprod, staging, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run build
